# Numpy tutorial  

Make sure `numpy` is already installed on your system (`pip install numpy`)

In [1]:
import numpy as np

## Create and Access array values

In [3]:
arr = np.array([
    [9.0, 8.0, 7.0],
    [6.0, 5.0, 4.0]
])

print(f"The number of dimensions = {arr.ndim} \nThe shape of arr is {arr.shape} \narr contains {arr.size} items of data type {arr.dtype}")

The number of dimensions = 2 
The shape of arr is (2, 3) 
arr contains 6 items of data type float64


In [4]:
arr

array([[9., 8., 7.],
       [6., 5., 4.]])

In [14]:
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        print(f"Element at {i},{j} = {arr[i][j]}")

Element at 0,0 = 9.0
Element at 0,1 = 8.0
Element at 0,2 = 7.0
Element at 1,0 = 6.0
Element at 1,1 = 5.0
Element at 1,2 = 4.0


In [15]:
arr[0, :]

array([9., 8., 7.])

In [17]:
arr[:, 1]

array([8., 5.])

## Special types of Arrays

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.full(
    (2,2),
    199
)

array([[199, 199],
       [199, 199]])

In [21]:
np.random.randint(low = -1,
 high = 100,
 size = (3,3)
)

array([[23, 89, 76],
       [ 1, 64,  5],
       [11, 85, 51]])

## Mathematics on Arrays

In [27]:
a = np.array([
        [1,2,3],
        [4,5,6]
    ])

print(a)

[[1 2 3]
 [4 5 6]]


In [28]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [29]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [32]:
np.min(a, axis = 0)

array([1, 2, 3])

In [33]:
np.min(a, axis = 1)

array([1, 4])

## Matrix Multiplication and Stacking 

In [37]:
m1 = np.ones((2,3))
print(m1)

m2 = np.full((3,2), 2.5)
print(m2)

mult = np.matmul(m1,m2)
print(mult)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2.5 2.5]
 [2.5 2.5]
 [2.5 2.5]]
[[7.5 7.5]
 [7.5 7.5]]


In [38]:
np.linalg.det(mult)

0.0

In [39]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## [Optional] Practise Problems

1. Find the inverse of a matrix
2. Find the trace of a matrix
3. Add and Subtract matrices